.\" -*- nroff -*-
.\"
.\" fmfconv.1: fmfconv man page
.\" Copyright (c) 2010-2013 Gergely Szasz
.\"
.\" This program is free software; you can redistribute it and/or modify
.\" it under the terms of the GNU General Public License as published by
.\" the Free Software Foundation; either version 2 of the License, or
.\" (at your option) any later version.
.\"
.\" This program is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public License along
.\" with this program; if not, write to the Free Software Foundation, Inc.,
.\" 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
.\"
.\" Author contact information:
.\"
.\" E-mail: szaszg@hu.inter.net
.\"
.\"
.TH fmfconv 1 "??th ?????, 201?" "Version 1.1.0" "Emulators"
.\"
.\"------------------------------------------------------------------
.\"
.SH NAME
fmfconv \(em Fuse movie file converter
.\"
.\"------------------------------------------------------------------
.\"
.SH SYNOPSIS
.B fmfconv
.RI [ options ]
.RI [ infile
.RI [ outfile
.RI [ soundfile ]]]
.\"
.\"------------------------------------------------------------------
.\"
.SH DESCRIPTION
fmfconv is a Fuse movie file converter. It can convert .fmf files to
any video file format known by FFMPEG.
...
.\"
.\"------------------------------------------------------------------
.\"
.SH OPTIONS
.PP
.RI "\-a "codec
.br
.RI "\-\-acodec "codec
.RS
Select audio codec for FFMPEG output (by default file format determine).
.RE
.PP
.RI \-\-acodecs
.RS
List available FFMPEG audio codecs (see \-a/\-\-acodec).
.RE
.PP
.RI \-\-aifc
.RS
Force AIFF-C output if sound format is AIFF.
.RE
.PP
.RI "\-A "rate
.br
.RI "\-\-arate "rate
.RS
Select audio bitrate for FFMPEG output (by default audio codec determine) 
where `rate' is `default' or a number.
.RE
.PP
.RI \-u
.br
.RI \-\-au
.RS
Save sound to Sun Audio (au) file.
.RE
.PP
.RI \-m
.br
.RI \-\-aiff
.RS
Save sound to Apple Computer audio (aiff/aiff-c) file.
.RE
.PP
.RI "\-F "format
.br
.RI "\-\-format "format
.RS
Select file format for FFMPEG output (by default the filename extension 
determines the format).
.RE
.PP
.RI \-\-formats
.RS
List available FFMPEG formats (see \-F/\-\-format).
.RE
.PP
.RI "\-f "timing
.br
.RI "\-\-frate "timing
.RS
Set output frame rate. `timing' is `pal', `ntsc', `movie' or a
number with maximum 3 digit after decimal point, or a #/# (e.g.: 
\-f 29.97 or \-f 30000/1001).
.RE
.PP
.RI \-h
.br
.RI \-\-help
.RS
Give brief usage help, listing available options.
.RE
.PP
.RI \-\-info
.RS
Scan input file(s) and print information.
.RE
.PP
.RI "\-i "filename
.br
.RI "\-\-input "filename
.RS
Input file.
.RE
.PP
.RI \-\-mono
.RS
Convert sound to mono (by default sound is converted to stereo).
.RE
.PP
.RI "\-C "cut
.br
.RI "\-\-out\-cut "cut
.RS
Leave out the comma delimited `cut' ranges e.g.: 100\-200,300,500,1:11\-2:22 
cut the frames 100\(en200, 300, 500 and frames from 1 min 11 sec to 2 min 22 sec 
(in the given timing see: \-f/\-\-frate).
.RE
.PP
.RI "\-o "filename
.br
.RI "\-\-output "filename
.RS
Output file.
.RE
.PP
.RI \-P
.br
.RI \-\-ppm
.RS
Save video as PPM screenshots.
.RE
.PP
.RI "\-p "profile
.br
.RI "\-\-profile "profile
.RS
Select the profile for FFMPEG output where <profile> is `youtube', `dvd', `svcd' 
or `ipod'.
.RE
.PP
.RI "\-g "form
.br
.RI "\-\-progress "form
.RS
Show progress, where <form> is one of `%', `bar', `frame' or `time'. frame and 
time are similar to bar and show movie seconds or frame number as well.
.RE
.PP
.RI \-q
.br
.RI \-\-quiet
.RS
Decrease the verbosity level by one.
.RE
.PP
.RI \-\-raw\-sound
.RS
Do not convert sound to 16-bit signed PCM and STEREO or MONO. This is an 
advanced option. If stereo/mono or audio encoding change through `fmf' file, 
your sound will be crappy.
.RE
.PP
.RI "\-R "res
.br
.RI "\-\-resize "res
.RS
Resize video frame where `res' is `vga' for 640x480, `hvga' for 480x360, `qvga' 
for 320x240, `pal' for 768x576 (this set frame rate to 25 also) or WxH, Sx, 
N/Mx or W.
.RE
.PP
.RI \-S
.br
.RI \-\-scr
.RS
Save video as SCR screenshots.
.RE
.PP
.RI "\-s "filename
.br
.RI "\-\-sound "filename
.RS
Output sound file.
.RE
.PP
.RI \-\-sound\-only
.RS
Process only the sound from an `fmf' file.
.RE
.PP
.RI "\-E "rate
.br
.RI "\-\-srate "rate
.RS
Resample audio to `rate' sampling rate where `rate' is `cd' for 44100 or `dat' 
for 48000 or a number (`cd' and `dat' set `stereo' as well).
.RE
.PP
.RI \-v
.br
.RI \-\-verbose
.RS
Increase the verbosity level by one.
.RE
.PP
.RI "\-c "codec
.br
.RI "\-\-vcodec "codec
.RS
Select video codec for FFMPEG output (by default file format determine).
.RE
.PP
.RI \-V
.br
.RI \-\-version
.RS
Print the version number and exit.
.RE
.PP
.RI "\-r "rate
.br
.RI "\-\-vrate "rate
.RS
Select video bitrate for FFMPEG output (by default audio codec determine) 
where `rate' is `default', `ffdefault' or a number.
.RE
.PP
.RI \-\-vcodecs
.RS
List available FFMPEG video codecs (see \-c/\-\-vcodec).
.RE
.PP
.RI \-w
.br
.RI \-\-wav
.RS
Save sound to Microsoft audio (wav) file.
.RE
.PP
.RI \-X
.br
.RI \-\-ffmpeg
.RS
Save video and audio as FFMPEG file (default if FFMPEG is available).
.RE
.PP
.RI \-Y
.br
.RI \-\-yuv
.RS
Save video as yuv4mpeg2.
.RE
.PP
.RI "\-\-yuv\-format "frm
.RS
Set yuv4mpeg2 file frame format to `frm', where `frm' is one of `444', 
`422', `420j', `420m', `420' or `410'.
.RE
.PP
.\"
.\"------------------------------------------------------------------
.\"
.SH BUGS
None known.
.\"
.\"------------------------------------------------------------------
.\"
.SH SEE ALSO
.IR ffmpeg "(1),"
.IR fuse "(1),"
.IR fuse\-utils "(1)"
.PP
The comp.sys.sinclair Spectrum FAQ, at
.br
.IR "http://www.worldofspectrum.org/faq/index.html" .
.\"
.\"------------------------------------------------------------------
.\"
.SH AUTHOR
Gergely Szasz.
